import { Icons } from '@components/Icon/Glyphs'

const exampleStringItems = [
  'First',
  'Second',
  'Third',
  'Fourth',
  'Fifth',
  'Sixth',
  'Seventh',
  'Eighth',
  'Ninth',
  'Tenth',
  'Eleventh',
  'Twelevth',
  'Thirteenth',
  'Fourteenth',
]

const exampleSimpleObjects = [
  { label: 'Oneth', value: 1 },
  { label: 'Twoth', value: 2 },
  { label: 'Thirth', value: 3 },
  { label: 'Fourst', value: 4 },
]

const examplePreformattedItems = [
  {
    label: 'First',
    subLabel: 'Pick the first item!',
    value: 1,
    leadingIcon: Icons.Apps,
    trailingIcon: Icons.ArrowRight,
  },
  {
    label: 'Second',
    subLabel: 'How about this one?',
    value: 2,
    leadingIcon: Icons.Archive,
    trailingIcon: Icons.CaretRight,
  },
  {
    label: 'Third',
    subLabel: 'This is what I have...',
    value: 3,
    leadingIcon: Icons.Automations,
    trailingIcon: Icons.ChevronRight,
  },
]

const exampleMappableItems = [
  {
    name: 'Alice Perkins',
    phoneNumber: 15557891420,
    id: 17086,
  },
  {
    name: 'Edward Heigl',
    phoneNumber: 15551470847,
    id: 14036,
  },
  {
    name: 'James Egert',
    phoneNumber: 15551564235,
    id: 69148,
  },
  {
    name: 'Laura Baker',
    phoneNumber: 15559472655,
    id: 18365,
  },
  {
    name: 'Marty Smith',
    phoneNumber: 15558305647,
    id: 23523,
  },
  {
    name: 'Steven Fredrickson',
    phoneNumber: 15558647562,
    id: 64785,
  },
]

const exampleCustomItems = [
  {
    make: 'Toyota',
    model: 'Prius',
    trimLevel: 'LE',
    modelYear: 2026,
    color: 'Wind Chill Pearl',
    condition: 'New',
    price: 32609,
    miles: 0,
  },
  {
    make: 'Kia',
    model: 'K4',
    trimLevel: 'LXS',
    modelYear: 2025,
    color: 'Steel Gray',
    condition: 'New',
    price: 22445,
    miles: 0,
  },
  {
    make: 'Mazda',
    model: 'MAZDA3',
    trimLevel: 'S Select Sport',
    modelYear: 2025,
    color: 'White',
    condition: 'New',
    price: 27315,
    miles: 0,
  },
  {
    make: 'Subaru',
    model: 'Impreza',
    trimLevel: 'Base',
    modelYear: 2025,
    color: 'Sapphire Blue Pearl',
    condition: 'New',
    price: 25140,
    miles: 0,
  },
  {
    make: 'Toyota',
    model: 'Corolla',
    trimLevel: 'LE',
    modelYear: 2025,
    color: 'Ice Cap',
    condition: 'New',
    price: 24409,
    miles: 0,
  },
  {
    make: 'Nissan',
    model: 'Versa',
    trimLevel: 'SV',
    modelYear: 2025,
    color: 'Gun Metallic',
    condition: 'Used',
    price: 18904,
    miles: 7796,
  },
  {
    make: 'Dodge',
    model: 'Charger',
    trimLevel: 'R/T',
    modelYear: 2023,
    color: 'White Knuckle Clearcoat',
    condition: 'Used',
    price: 38957,
    miles: 13044,
  },
  {
    make: 'Subaru',
    model: 'BRZ',
    trimLevel: 'Limited',
    modelYear: 2023,
    color: 'Ice Silver Metallic',
    condition: 'Used',
    price: 29961,
    miles: 6939,
  },
  {
    make: 'Toyota',
    model: 'Camry',
    trimLevel: 'XSE',
    modelYear: 2023,
    color: 'Silver',
    condition: 'Used',
    price: 23389,
    miles: 61035,
  },
  {
    make: 'Nissan',
    model: 'Sentra',
    trimLevel: 'SV',
    modelYear: 2022,
    color: 'Fresh Powder',
    condition: 'Used',
    price: 17499,
    miles: 42626,
  },
  {
    make: 'Ford',
    model: 'Fusion',
    trimLevel: 'SE',
    modelYear: 2020,
    color: 'Red',
    condition: 'Used',
    price: 16198,
    miles: 71005,
  },
  {
    make: 'Chevrolet',
    model: 'Trax',
    trimLevel: 'LT',
    modelYear: 2019,
    color: 'Mosaic Black Metallic',
    condition: 'Used',
    price: 15990,
    miles: 65806,
  },
  {
    make: 'Hyundai',
    model: 'Elantra',
    trimLevel: 'Value Edition',
    modelYear: 2018,
    color: 'Lakeside Blue',
    condition: 'Used',
    price: 12653,
    miles: 95008,
  },
  {
    make: 'Hyundai',
    model: 'Sonata',
    trimLevel: 'Sport+',
    modelYear: 2018,
    color: 'Scarlet Red',
    condition: 'Used',
    price: 12225,
    miles: 106501,
  },
]

export {
  exampleStringItems,
  exampleSimpleObjects,
  examplePreformattedItems,
  exampleMappableItems,
  exampleCustomItems,
}
