// this file will contain all the props for shared layout components

const layoutProps = {
  gap: {
    '1': 'gap-1',
    '2': 'gap-2',
    '3': 'gap-3',
    '4': 'gap-4',
    '5': 'gap-5',
    '6': 'gap-6',
    '7': 'gap-7',
    '8': 'gap-8',
    '9': 'gap-9',
    '10': 'gap-10',
    '11': 'gap-11',
    '12': 'gap-12',
    none: 'gap-none',
  },
  gapX: {
    '1': 'gap-x-1',
    '2': 'gap-x-2',
    '3': 'gap-x-3',
    '4': 'gap-x-4',
    '5': 'gap-x-5',
    '6': 'gap-x-6',
    '7': 'gap-x-7',
    '8': 'gap-x-8',
    '9': 'gap-x-9',
    '10': 'gap-x-10',
    '11': 'gap-x-11',
    '12': 'gap-x-12',
    none: 'gap-x-none',
  },
  gapY: {
    '1': 'gap-y-1',
    '2': 'gap-y-2',
    '3': 'gap-y-3',
    '4': 'gap-y-4',
    '5': 'gap-y-5',
    '6': 'gap-y-6',
    '7': 'gap-y-7',
    '8': 'gap-y-8',
    '9': 'gap-y-9',
    '10': 'gap-y-10',
    '11': 'gap-y-11',
    '12': 'gap-y-12',
    none: 'gap-y-none',
  },
  justify: {
    start: 'justify-start',
    center: 'justify-center',
    end: 'justify-end',
    stretch: 'justify-stretch',
    between: 'justify-between',
    around: 'justify-around',
    evenly: 'justify-evenly',
  },
  align: {
    start: 'items-start',
    center: 'items-center',
    end: 'items-end',
    stretch: 'items-stretch',
  },
  alignContent: {
    start: 'content-start',
    center: 'content-center',
    end: 'content-end',
    stretch: 'content-stretch',
  },
  alignSelf: {
    auto: 'self-auto',
    start: 'self-start',
    center: 'self-center',
    end: 'self-end',
    stretch: 'self-stretch',
  },
  order: {
    '1': 'order-1',
    '2': 'order-2',
    '3': 'order-3',
    '4': 'order-4',
    '5': 'order-5',
    '6': 'order-6',
    '7': 'order-7',
    '8': 'order-8',
    '9': 'order-9',
    '10': 'order-10',
    none: 'order-none',
  },
}

export { layoutProps }
