declare const heightKeys: readonly ["h", "min-h", "max-h"];
declare const heightProps: {
    h: {
        full: string;
        screen: string;
        auto: string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '10': string;
        '11': string;
        '24': string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
    };
    hMin: {
        full: string;
        screen: string;
        auto: string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '10': string;
        '11': string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
    };
    hMax: {
        full: string;
        screen: string;
        auto: string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '10': string;
        '11': string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
    };
};
export { heightProps, heightKeys };
