declare const pixelSizeProps: {
    size: {
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '10': string;
        '11': string;
        '12': string;
        '14': string;
        '16': string;
        '20': string;
        '24': string;
        '28': string;
        '32': string;
        '36': string;
        '40': string;
        '44': string;
        '48': string;
        '52': string;
        '56': string;
        '60': string;
        '64': string;
        '72': string;
        '80': string;
        '96': string;
    };
};
declare const sizeProps: {
    size: {
        full: string;
        screen: string;
        auto: string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '10': string;
        '11': string;
        '12': string;
        '14': string;
        '16': string;
        '20': string;
        '24': string;
        '28': string;
        '32': string;
        '36': string;
        '40': string;
        '44': string;
        '48': string;
        '52': string;
        '56': string;
        '60': string;
        '64': string;
        '72': string;
        '80': string;
        '96': string;
    };
};
export type sizeNameProps = 'tiny' | 'small' | 'medium' | 'large' | 'huge';
export { sizeProps, pixelSizeProps };
