declare const widthKeys: readonly ["w", "min-w", "max-w"];
declare const widthProps: {
    w: {
        full: string;
        screen: string;
        auto: string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '10': string;
        '11': string;
        '12': string;
        '13': string;
        '14': string;
        '15': string;
        '16': string;
        '20': string;
        '24': string;
        '28': string;
        '32': string;
        '36': string;
        '40': string;
        '44': string;
        '48': string;
        '52': string;
        '56': string;
        '60': string;
        '64': string;
        '72': string;
        '80': string;
        '96': string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
    };
    wMin: {
        full: string;
        screen: string;
        auto: string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
    };
    wMax: {
        full: string;
        screen: string;
        auto: string;
        '0': string;
        '1': string;
        '2': string;
        '3': string;
        '4': string;
        '5': string;
        '6': string;
        '7': string;
        '8': string;
        '9': string;
        '1/4': string;
        '1/3': string;
        '1/2': string;
        '2/3': string;
        '3/4': string;
    };
};
declare const spacingRemMap: Record<string, number>;
export { widthProps, widthKeys, spacingRemMap };
